django_blog_it/django_blog_it/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', admin_login, name='admin_login'),
    url(r'^logout/$', admin_logout, name='admin_logout'),

    # Blog
    url(r'^blog/$', PostList.as_view(), name='blog'),
    url(r'^add/$', PostCreatView.as_view(), name='blog_add'),
    url(r'^view/(?P<blog_slug>[-\w]+)/$', PostDetailView.as_view(), name='view_blog'),
    url(r'^delete/(?P<blog_slug>[-\w]+)/$', PostDeleteView.as_view(), name='delete_blog'),
    url(r'^edit/(?P<blog_slug>[-\w]+)/$', edit_blog, name='edit_blog'),

    # Categories
    url(r'^add_category/$', add_category, name='add_category'),
    url(r'^category/$', categories, name='categories'),
    url(r'^delete_category/(?P<category_slug>[-\w]+)/$', delete_category, name='delete_category'),
    url(r'^edit_category/(?P<category_slug>[-\w]+)/$', edit_category, name='edit_category'),

    url(r'^bulk_actions_menu/$', bulk_actions_menu, name='bulk_actions_menu'),
    url(r'^bulk_actions_blog/$', bulk_actions_blog, name='bulk_actions_blog'),
    url(r'^bulk_actions_category/$', bulk_actions_category, name='bulk_actions_category'),
    url(r'upload_photos/$', upload_photos, name='upload_photos'),
    url(r'recent_photos/$', recent_photos, name='recent_photos'),
]

django_blog_it/django_blog_it/forms.py
from django import forms
from .models import Post, Category, ContactUsSettings, ROLE_CHOICE, Theme
from django.template.defaultfilters import slugify
# for authentication
from django.contrib.auth import authenticate
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(required=False, widget=forms.PasswordInput)
    role = forms.ChoiceField(choices=ROLE_CHOICE, required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'is_active')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if self.instance.id:
            if User.objects.filter(email=email, username=username).exclude(id=self.instance.id).count():
                raise forms.ValidationError(u'Email addresses must be unique.')
        else:
            if User.objects.filter(email=email).exclude(username=username).count():
                raise forms.ValidationError(u'Email addresses must be unique.')
        return email

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        for field in iter(self.fields):
            if max(enumerate(iter(self.fields)))[0] != field:
                self.fields[field].widget.attrs.update({
                    'class': 'form-control',
                    "placeholder": "Please enter your " + field.capitalize()
                })

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        password = self.cleaned_data["password"]
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user


class AdminLoginForm(forms.Form):
    username = forms.CharField(max_length=254)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if user is None:
                raise forms.ValidationError("Incorrect Login Details")

        return self.cleaned_data


class BlogPostForm(forms.ModelForm):
    tags = forms.CharField(label="Tags", max_length=300, required=False)

    class Meta:
        model = Post
        exclude = ('slug', 'user', 'tags')

    def __init__(self, *args, **kwargs):
        self.user_role = kwargs.pop('user_role', None)
        super(BlogPostForm, self).__init__(*args, **kwargs)

        if self.user_role == 'Author':
            del self.fields['status']

        for field in iter(self.fields):
            if field == 'tags':
                self.fields[field].widget.attrs.update({
                    'class': 'form-control myTags', "placeholder": "Please enter your Blog " + field.capitalize()
                })
            else:
                self.fields[field].widget.attrs.update({
                    'class': 'form-control', "placeholder": "Please enter your Blog " + field.capitalize()
                })
        if self.instance and self.instance.id:
            tags_value = ",".join([tag.name for tag in self.instance.tags.all()])
            self.fields['tags'].initial = tags_value
        self.fields['category'].queryset = Category.objects.filter(is_active=True)

    def clean_status(self):
        if self.user_role == "Author":
            raise forms.ValidationError("Admin and Publisher can change status only.")
        return self.cleaned_data.get("status")


class BlogCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude = ('slug',)

    def clean_name(self):
        if not self.instance.id:
            if Category.objects.filter(slug=slugify(self.cleaned_data['name'])).exists():
                raise forms.ValidationError('Category with this Name already exists.')
        else:
            if Category.objects.filter(name__icontains=self.cleaned_data['name']).exclude(id=self.instance.id):
                raise forms.ValidationError('Category with this Name already exists.')

        return self.cleaned_data['name']

    def __init__(self, *args, **kwargs):
        super(BlogCategoryForm, self).__init__(*args, **kwargs)

        for field in iter(self.fields):
            if max(enumerate(iter(self.fields)))[0] != field:
                self.fields[field].widget.attrs.update({
                    'class': 'form-control', "placeholder": "Please enter your Category " + field.capitalize()
                })


class UserRoleForm(forms.Form):
    role = forms.CharField(max_length=10)


class ContactUsSettingsForm(forms.ModelForm):

    class Meta:
        model = ContactUsSettings
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(ContactUsSettingsForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            if max(enumerate(iter(self.fields)))[0] != field:
                self.fields[field].widget.attrs.update({
                    'class': 'form-control',
                    "placeholder": "Please enter your " + field.replace('_', ' ').capitalize()
                })


class BlogThemeForm(forms.ModelForm):

    class Meta:
        model = Theme
        exclude = ('slug',)
        widgets = {
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(BlogThemeForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                "placeholder": "Please enter your Theme " + field.capitalize()
            })


class ContactForm(forms.Form):
    contact_name = forms.CharField(max_length=128, required=True)
    contact_email = forms.EmailField(required=True)
    contact_website = forms.URLField(
        max_length=200, required=True, help_text="Enter Your Website URL here")
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

    def clean(self):
        cleaned_data = super(ContactForm, self).clean()
        contact_website = cleaned_data.get('contact_website')

        if contact_website and not contact_website.startswith('http://'):
            contact_website = 'http://' + contact_website
            cleaned_data['contact_website'] = contact_website

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['contact_name'].widget.attrs['placeholder'] = "Enter Your Name (Required)"
        self.fields['contact_email'].widget.attrs['placeholder'] = "Enter Your Email (Required)"
        self.fields['contact_website'].widget.attrs['placeholder'] = "Enter Your Website (Required)"
        self.fields['content'].widget.attrs['placeholder'] = "What do you want to say?"
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class ChangePasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}))

    def clean_confirm_password(self):
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match!!!")
        return confirm_password


class CustomBlogSlugInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super(CustomBlogSlugInlineFormSet, self).clean()
        if any(self.errors):
            return
        active_slugs = 0
        for form in self.forms:
            if form.cleaned_data.get("is_active"):
                active_slugs += 1
        if active_slugs > 1:
            raise forms.ValidationError("Only one slug can be active at a time.")

django_blog_it/django_blog_it/templates/dashboard/blog/new_blog_add.html
{% extends 'dashboard/new_base.html' %}
{% load static %}
{% block title %}
  {% if add_blog %}Add{% else %}Edit{% endif %} Blog
{% endblock %}
{% block extra_css %}
{% endblock %}
{% block content %}
  <div class="row no_row_margin heading_count">
    <div class="heading col-md-6" id='page_title'></div>
  </div>
  <div class="row no_row_margin">
    <div class="container-fluid">
      <form action="" method="post" enctype="multipart/form-data" id="post-form" role="form" novalidate>
        {% csrf_token %}
        <div class="row form_row no_row_margin">
          <div class="col-md-12">
            <div class="col-md-6">
              {% for field in form %}
                {% if field.name != 'content' %}
                  <div class="form-group">
                    <label>{% if field.name == 'title' %}POST TITLE{% else %}{{ field.label }}{% endif %}</label>
                    <div class="controls">
                      {{ field }}
                      {% if field.help_text %}
                      <p class="help-inline"><small>{{ field.help_text }}</small></p>
                      {% endif %}
                    </div>
                  </div>
                {% endif %}
              {% endfor %}
              {% if form.instance.id %}
                <div class="form-group">
                  <label>History:</label>
                  <div class="controls">
                    <select name="history" class="form-control">
                      <option value=""> Please choose previous edit </option>
                      {% for history in history_list %}
                        <option value="{{history.id}}">{{ history.created_at }}</option>
                      {% endfor %}
                    </select>
                    <p class="help-inline"><small>Revert to previous edits</small></p>
                  </div>
                </div>
              {% endif %}
            </div>
            <div class="col-md-6">
              {% for field in form %}
                {% if field.name == 'content' %}
                  <div class="form-group">
                    <label>Description</label>
                    <div class="controls">
                      {{ field }}
                      {% if field.help_text %}
                      <p class="help-inline"><small>{{ field.help_text }}</small></p>
                      {% endif %}
                    </div>
                  </div>
                {% endif %}
              {% endfor %}
            </div>
          </div>
          <div class="col-md-12">
            {{ formset.management_form }}
            {% for form in formset %}
              <div class="col-md-12 slug">
                {{ form }}
              </div>
            {% endfor %}
          </div>
          <br clear="all">
          <div class=" col-md-12 buttons_row text-left">
            <button type="submit" class="btn btn-default green_btn"> <i class="fa fa-floppy-o" aria-hidden="true"></i> Save</button>
            <button type="reset" class="btn btn-default blue_btn"> <i class="fa fa-refresh" aria-hidden="true"></i> Reset</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <!-- end of add form div -->
{% endblock %}
{% block js_script %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {

      // for form submission
      /*CKEDITOR.replace('content', {
        filebrowserUploadUrl: '{% url "upload_photos" %}',
        filebrowserBrowseUrl: '{% url "recent_photos" %}',
        uiColor: '#ffffff',
        height: 475,
      });*/

      ClassicEditor
        .create(document.querySelector('#id_content'))
        .then(newEditor => {
          window.editor = newEditor;
        })
        .catch(error => {
          console.error(error);
        });

      /*// Assuming there is a <button id="submit">Submit</button> in your application.
      document.querySelector( '#submit' ).addEventListener( 'click', () => {
          const editorData = editor.getData();

          // ...
      } );*/


      $('form#post-form').ajaxForm({
        beforeSerialize: function() {
          $('#id_content').val(window.editor.getData());
        },

        dataType: 'json',
        success: function(data) {
          if (data.error) {
            $('p.error_required').remove();
            for (var key in data.response) {
              $('#id_' + key).after('<p class="error_required">* ' + data.response[key] + '</p>');
            }
          } else {
            console.log("Redirection url", "{% url 'blog' %}")
            window.location.href = "{% url 'blog' %}";
          }
        }
      });
      //  script for form submission ends here


      // for page title

      if (window.location.pathname == "{% url 'blog_add' %}") {
        $('#page_title').text('Add Blog');
      } else {
        var blog = '{{ blog_name.title }}';
        $('#page_title').text('Edit Blog: ' + blog);
      }

      //script for page title ends here

      // for tags

      function onAddTag(tag) {
        alert("Added a tag: " + tag);
      }

      function onRemoveTag(tag) {
        alert("Removed a tag: " + tag);
      }

      function onChangeTag(input, tag) {
        alert("Changed a tag: " + tag);
      }

      $(function() {
        $('.myTags').tagsInput({ width: 'auto' });
      });

      // script for tags ends here

    });

    // revert to history
    $("select[name=history]").change(function(e) {
      var id = $(this).val()
      if (!id) {
        return false;
      }
      $.post("", { "history_id": id, "csrfmiddlewaretoken": "{{ csrf_token }}" }, function(response) {
        if (response.content) {
          $('[name=content]').html(response.content);
          window.editor.setData(response.content)
        }
      })
    });
  </script>
{% endblock %}

django_blog_it/django_blog_it/templates/dashboard/blog/new_blog_list.html
{% extends 'dashboard/new_base.html' %}
{% load blog_tags %}
{% load paginate %}
{% block title %}Posts{% endblock %}
{% block extra_css %}
  <style type="text/css">
    table td {
      padding: 6px;
    }
  </style>
  {% endblock %}
{% block content %}
  <div class="row no_row_margin heading_count">
    <div class="heading col-md-6">Blogs</div>
    <div class="count_add-new col-md-6 text-right">
      <ul class="list-inline">
        <li><a href="#">All ({{ blog_list|length }}) </a></li>
        <li><a href="#">Published ({{ published_blogs|length }}) </a></li>
      </ul>
      <span class="add_new"><a href="{% url 'blog_add' %}"><i class="fa fa-plus"></i> Add Blog</a></span>
    </div>
  </div>
  <div class="filters_row">
    <div class="col-md-6 filter_left">
      {% if request.user.is_superuser or request.user.userrole_set.last.role == "Admin"%}
      <div class="bulk_button" style="display:none">
        <form class="bulk_actions_form" method='get'>
          {% csrf_token %}
          <select class="form-control" name="bulk_actions_select" id='bulk_actions_select'>
            <option>Choose An Action</option>
            {% for key, choice in blog_choices %}
            <option value="{{ key }}">{{ choice }}</option>
            {% endfor %}
          </select>
          <button class="btn btn-default" type="submit">Apply Action</button>
        </form>
      </div>
      {% endif %}
    </div>
    <div class="col-md-6 filter_right">
      <form action="" method="post" id="blogs_data" class="form-inline">
        {% csrf_token %}
        <input type="text" placeholder="Filter By Title" value="{% if request.POST %}{{ request.POST.search_text }}{% endif %}" name='search_text' class="form-control" />
        <select class="form-control" id="select_status" name="select_status">
          <option value="" default>Status</option>
          {% for key, choice in blog_choices %}
            <option value="{{ key }}" {% ifequal key request.POST.select_status %}selected{% endifequal %}>{{ choice }}</option>
          {% endfor %}
        </select>
        <button class="btn btn-default" type="submit">Apply Filter</button>
      </form>
    </div>
    <br clear="all">
  </div>
  {% if blog_list %}
  <div class="row no_row_margin table_row">
    <div class="container-fluid">
      {% paginate 5 blog_list %}
      {% show_pageitems %}
      {% with request.user.userrole_set.last as user_role %}
        <table class="table table-bordered table-striped" id="my_table">
          <thead>
            <tr>
              {% if request.user.is_superuser or user_role.role == "Admin"%}
                <th width="5%" class="text-center"><input name="bulk_actions" id="selectAll" type="checkbox"></th>
              {% endif %}
              <th width="30%">Title</th>
              <th width="10%">Author</th>
              <th width="15%">Category</th>
              <th width="15%">Status</th>
              <th width="25%" colspan="3">Actions</th>
            </tr>
          </thead>
          {% for blog in blog_list %}
            <tbody>
              <tr>
                {% if request.user.is_superuser or user_role.role == "Admin"%}
                  <td class="text-center"><input name="bulk_actions" class="bulk_actions" value="{{ blog.id }}" type="checkbox">
                </td>
                {% endif %}
                <td><a href="#">{{ blog.title }}</a></td>
                <td>{{ blog.user }}</td>
                <td>{{ blog.category }}</td>
                <td id="blog_status">
                  {% if blog.status == "Published" %}
                  <i class="fa fa-thumbs-up"></i> {{ blog.status }}
                  {% elif blog.status == "Drafted" %}
                  <i class="fa fa-file-o"></i> {{ blog.status }}
                  {% elif blog.status == "Trashed" %}
                  <i class="fa fa-trash-o"></i> {{ blog.status }}
                  {% else %}
                  <i class="fa fa-thumbs-down"></i> {{ blog.status }}
                  {% endif %}
                </td>
                <td class="actions" colspan="3">
                  {% if blog|is_deletable_by:request.user or request.user|get_user_role_name != 'Author' %}
                  <form class="blog_trash_form" role="form" method="POST" action="{% url 'delete_blog' blog_slug=blog.slug %}">
                    {% csrf_token %}
                    <input type="hidden" name="action">
                  </form>
                  {% endif %}
                  <a href="{% url 'view_blog' blog_slug=blog.slug %}" class="view"><i class="fa fa-eye"></i> View</a>
                  {% if blog|is_deletable_by:request.user or request.user|get_user_role_name != 'Author' %}
                  <a href="{% url 'edit_blog' blog_slug=blog.slug %}" class="edit"><i class="fa fa-edit"></i> Edit</a>
                  {% endif %}
                  {% if request.user.is_superuser or request.user|get_user_role_name != 'Author' or blog.user == request.user %}
                  {% ifequal blog.status "Trashed" %}
                  <a href='#' class="restore manage_blog" action="restore" title="Restore from trash"><i class="fa fa-refresh"></i> Restore</a>
                  <a href='#' class="delete manage_blog" action="delete" title="Permanently delete from trash" data-confirm="true"><i class="fa fa-trash-o"></i> Delete</a>
                  {% else %}
                  <a href='#' class="trash manage_blog" action="trash" title="Move to Trash"><i class="fa fa-times"></i> Trash</a>
                  {% endifequal %}
                  {% endif %}
                </td>
              </tr>
            </tbody>
          {% endfor %}
        </table>
      {% endwith %}
      <!-- end div of table -->
      <!-- pagination -->
      <div class="pagination_wrap text-center">
        {% show_pages %}
      </div>
      <!--/ pagination -->
    </div>
  </div>
  {% else %}
    <div class="row no_row_margin table_row">
      <div class="container-fluid">
        <h2 align="center"> There are no blog-posts here !</h2>
      </div>
    </div>
  {% endif %}
{% endblock %}
{% block delete_confirmation %}
{% endblock delete_confirmation %}
{% block js_script %}
  <script type="text/javascript">
    $('.dashboard').addClass('active');
    $('.manage_blog').click(function(e) {
      e.preventDefault();
      if ($(this).attr('action') == 'delete') {
        var confirmation = confirm("Are you sure?");
        if (confirmation) {
          $(this).siblings("form.blog_trash_form").children("input[name='action']").val($(this).attr('action'));
        } else {
          return
        }
      } else {
        $(this).siblings("form.blog_trash_form").children("input[name='action']").val($(this).attr('action'));
      }
      $(this).siblings("form.blog_trash_form").submit();
    });
    $('.select2_blog').select2({ placeholder: 'Select Blogs' });
    $("#selectAll").change(function() {
      // $(".bulk_button").toggle();
      $(".bulk_actions:checkbox").prop('checked', $(this).prop("checked"));
      if ($(this).prop("checked")) {
        $(".bulk_button").show();
      } else {
        $(".bulk_button").hide();
      }
    });

    $(".bulk_actions:checkbox").change(function() {
      if ($(this).attr("id") != "selectAll") {
        if ($(".bulk_actions:checkbox:checked").length > 0) {
          $(".bulk_button").show();
        } else {
          $("#selectAll").prop('checked', false);
          $(".bulk_button").hide();
        }
      }
    });

    $('.bulk_actions_form').submit(function(e) {
      e.preventDefault();
      var blog_ids = [];
      $.each($(".bulk_actions:checked"), function() {
        blog_ids.push(parseInt($(this).val(), 0));
      });
      var action = $('#bulk_actions_select :selected').val();

      $.get("{% url 'bulk_actions_blog' %}", { 'blog_ids': blog_ids, 'action': action }, function(data) {
        if (data.response) {
          window.location = "{% url 'blog' %}";
        } else {
          window.location = "{% url 'blog' %}";
        }
      }, 'json');
    })

    $('.pagination li a').click(function(event) {
      event.preventDefault();
      console.log($(this).attr('href'));
      $('#blogs_data').attr('action', $(this).attr('href'));
      $('#blogs_data').submit();
    });
  </script>
{% endblock %}

django_blog_it/django_blog_it/templates/dashboard/blog/new_blog_view.html
{% extends 'dashboard/new_base.html' %}
{% block title %}Posts View{% endblock %}
{% block content %}
  <div class="row no_row_margin table_row">
    <div class="container-fluid">
      <table align="center" class="table table-bordered">
        <thead>
          <th>
            Title: {{ blog_post.title }}
          </th>
        </thead>
        <tbody>
          <tr>
            <td><strong>Author</strong>: {{ blog_post.user }}</td>
          </tr>
          <tr>
            <td><strong>Content</strong>: {{ blog_post.content|safe }}</td>
          </tr>
          <tr>
            <td><strong>Status</strong>: {{ blog_post.status }}</td>
          </tr>
          <tr>
            <td><strong>Tags</strong>: {% for tag in blog_post.tags.all %}{{ tag }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
          </tr>
          <tr>
            <td><strong>Keywords</strong>: {{ blog_post.keywords|safe }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <!-- end div of row -->
{% endblock %}