django_blog_it/django_blog_it/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', admin_login, name='admin_login'),
    url(r'^logout/$', admin_logout, name='admin_logout'),

    # Blog
    url(r'^blog/$', PostList.as_view(), name='blog'),
    url(r'^add/$', PostCreatView.as_view(), name='blog_add'),
    url(r'^view/(?P<blog_slug>[-\w]+)/$', PostDetailView.as_view(), name='view_blog'),
    url(r'^delete/(?P<blog_slug>[-\w]+)/$', PostDeleteView.as_view(), name='delete_blog'),
    url(r'^edit/(?P<blog_slug>[-\w]+)/$', edit_blog, name='edit_blog'),

    # Categories
    url(r'^add_category/$', add_category, name='add_category'),
    url(r'^category/$', categories, name='categories'),
    url(r'^delete_category/(?P<category_slug>[-\w]+)/$', delete_category, name='delete_category'),
    url(r'^edit_category/(?P<category_slug>[-\w]+)/$', edit_category, name='edit_category'),

    url(r'^bulk_actions_menu/$', bulk_actions_menu, name='bulk_actions_menu'),
    url(r'^bulk_actions_blog/$', bulk_actions_blog, name='bulk_actions_blog'),
    url(r'^bulk_actions_category/$', bulk_actions_category, name='bulk_actions_category'),
    url(r'upload_photos/$', upload_photos, name='upload_photos'),
    url(r'recent_photos/$', recent_photos, name='recent_photos'),
]

django_blog_it/django_blog_it/models.py
import datetime
import os
from django.db import models
from django.template.defaultfilters import slugify
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail


ROLE_CHOICE = (
    ('Admin', 'Admin'),
    ('Publisher', 'Publisher'),
    ('Author', 'Author'),
)

STATUS_CHOICE = (
    ('Drafted', 'Drafted'),
    ('Published', 'Published'),
    ('Rejected', 'Rejected'),
    ('Trashed', 'Trashed'),
)


class UserRole(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    role = models.CharField(max_length=10, choices=STATUS_CHOICE)

    class Meta:
        ordering = ['-id']


class Theme(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=500)
    enabled = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Theme, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=500)
    is_active = models.BooleanField(default=False)
    meta_description = models.TextField(max_length=160, null=True, blank=True)
    meta_keywords = models.TextField(max_length=255, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-id']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def category_posts(self):
        return Post.objects.filter(category=self).count()


class Tags(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.CharField(max_length=20, unique=True)

    def save(self, *args, **kwargs):
        tempslug = slugify(self.name)
        if self.id:
            tag = Tags.objects.get(pk=self.id)
            if tag.name != self.name:
                self.slug = create_tag_slug(tempslug)
        else:
            self.slug = create_tag_slug(tempslug)
        super(Tags, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


def create_tag_slug(tempslug):
    slugcount = 0
    while True:
        try:
            Tags.objects.get(slug=tempslug)
            slugcount += 1
            tempslug = tempslug + '-' + str(slugcount)
        except ObjectDoesNotExist:
            return tempslug


class Post(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)
    meta_description = models.TextField(max_length=160, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tags, related_name='rel_posts')
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='Drafted')
    keywords = models.TextField(max_length=500, blank=True)
    featured_image = models.ImageField(upload_to='static/blog/uploads/%Y/%m/%d/', blank=True, null=True)

    class Meta:
        ordering = ['-updated_on']

    def save(self, *args, **kwargs):
        tempslug = slugify(self.title)
        if self.id:
            blogpost = Post.objects.get(pk=self.id)
            if blogpost.title != self.title:
                self.slug = create_slug(tempslug)
        else:
            self.slug = create_slug(tempslug)
            self.email_to_admins_on_post_create()

        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def is_deletable_by(self, user):
        if self.user == user or user.is_superuser:
            return True
        return False

    def create_activity(self, user, content):
        return PostHistory.objects.create(
            user=user, post=self, content=content
        )

    def create_activity_instance(self, user, content):
        return PostHistory(
            user=user, post=self, content=content
        )

    def remove_activity(self):
        self.history.all().delete()

    def email_to_admins_on_post_create(self):
        email = os.getenv("DEFAULT_EMAIL")
        if not self.id and email:
            admin_roles = UserRole.objects.select_related().filter(role="Admin")
            admin_emails = [admin_role.user.email for admin_role in admin_roles]
            user = self.user
            author_name = user.first_name + user.last_name if user.first_name else user.email
            text = "New blog post has been created by {0} with the name {1} in the category {2}.".format(
                author_name, self.title, self.category.name)
            send_mail(
                subject="New Blog Post created",
                message=text,
                from_email=email,
                recipient_list=admin_emails,
                fail_silently=False,
            )

    def store_old_slug(self, old_slug):
        query = Post_Slugs.objects.filter(blog=self, slug=old_slug).values_list("slug", flat=True)
        if not (query and old_slug != self.slug):
            old_slug, _ = Post_Slugs.objects.get_or_create(blog=self, slug=old_slug)
            old_slug.is_active = False
            old_slug.save()
        active_slug, _ = Post_Slugs.objects.get_or_create(blog=self, slug=self.slug)
        active_slug.is_active = True
        active_slug.save()


def create_slug(tempslug):
    slugcount = 0
    while True:
        try:
            Post.objects.get(slug=tempslug)
            slugcount += 1
            tempslug = tempslug + '-' + str(slugcount)
        except ObjectDoesNotExist:
            return tempslug


class Post_Slugs(models.Model):
    blog = models.ForeignKey(Post, related_name='slugs', on_delete=models.CASCADE)
    slug = models.SlugField(max_length=100, unique=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.slug


class PostHistory(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='history', on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{username} {content} {blog_title}'.format(
            username=str(self.user.get_username()),
            content=str(self.content),
            blog_title=str(self.post.title)
        )


class Image_File(models.Model):
    upload = models.FileField(upload_to="static/uploads/%Y/%m/%d/")
    date_created = models.DateTimeField(default=datetime.datetime.now)
    is_image = models.BooleanField(default=True)
    thumbnail = models.FileField(upload_to="static/uploads/%Y/%m/%d/", blank=True, null=True)

    def __str__(self):
        return self.date_created


class ContactUsSettings(models.Model):
    from_email = models.EmailField()
    reply_to_email = models.EmailField(blank=True, null=True)
    email_admin = models.EmailField()
    subject = models.CharField(max_length=500)
    body_user = models.TextField()
    body_admin = models.TextField()


class Google(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='google', on_delete=models.CASCADE)
    google_id = models.CharField(max_length=200, default='')
    google_url = models.CharField(max_length=1000, default='')
    verified_email = models.CharField(max_length=200, default='')
    family_name = models.CharField(max_length=200, default='')
    name = models.CharField(max_length=200, default='')
    picture = models.CharField(max_length=200, default='')
    gender = models.CharField(max_length=10, default='')
    dob = models.CharField(max_length=50, default='')
    given_name = models.CharField(max_length=200, default='')
    email = models.CharField(max_length=200, default='', db_index=True)

    def __str__(self):
        return self.email


class Facebook(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='facebook', on_delete=models.CASCADE)
    facebook_id = models.CharField(max_length=100)
    facebook_url = models.CharField(max_length=200, default='')
    first_name = models.CharField(max_length=200, default='')
    last_name = models.CharField(max_length=200, default='')
    verified = models.CharField(max_length=200, default='')
    name = models.CharField(max_length=200, default='')
    language = models.CharField(max_length=200, default='')
    hometown = models.CharField(max_length=200, default='')
    email = models.CharField(max_length=200, default='', db_index=True)
    gender = models.CharField(max_length=200, default='')
    dob = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=200, default='')
    timezone = models.CharField(max_length=200, default='')
    accesstoken = models.CharField(max_length=2000, default='')

    def __str__(self):
        return self.email

django_blog_it/django_blog_it/templates/dashboard/user/change_password.html
{% extends 'dashboard/new_base.html' %}
{% block title %}
  Change Password
{% endblock %}
{% block content %}
  <div class="row no_row_margin heading_count">
    <div class="heading col-md-6" id='page_title'>
      Change Password
    </div>
  </div>
  <!-- end class of row -->
  <div class="row no_row_margin">
    <div class="container-fluid">
      <form action="" id="post-form" enctype="multipart/form-data" method="post" role="form" novalidate>
        {% csrf_token %}
        <div class="row form_row no_row_margin">
          <div class="col-md-12">
            <div class="col-md-6">
              {% for field in form %}
                <div class="form-group col-md-12">
                  <label>{{ field.label }} :</label>
                  <div class="controls">
                    {{ field }}
                    {% if field.help_text %}
                    <p class="help-inline"><small>{{ field.help_text }}</small></p>
                    {% endif %}
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
          <br clear="all">
          <div class=" col-md-12 buttons_row text-left">
            <div class="form-group">
              <button type="submit" class="btn btn-default green_btn"> <i class="fa fa-floppy-o" aria-hidden="true"></i> Submit</button>
              <button type="reset" class="btn btn-default blue_btn"> <i class="fa fa-refresh" aria-hidden="true"></i> Reset</button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
  <!-- end div row of form -->
{% endblock %}
{% block js_script %}
  <script type="text/javascript">
    $('#post-form').submit(function(event) {
      event.preventDefault()
      $.post("", $(this).serialize(), function(response) {
        $('.error').remove();
        if (response.error) {
          $.each(response.errors, function(name, error) {
            $("[name=" + name + "]").after("<span class='error'>" + error + "</span>")
          });
        } else {
          window.location = response.success_url
        }
      }, 'json');
    });
  </script>
{% endblock %}

django_blog_it/django_blog_it/templates/dashboard/user/new_add_user.html
{% extends 'dashboard/new_base.html' %}
{% block title %}
  {% if user %}Add{% else %}Edit{% endif %} Page
{% endblock %}
{% block content %}
  <div class="row no_row_margin heading_count">
    <div class="heading col-md-6" id='page_title'>
      {% if user %}Edit {{ user.username }} {% else %}Add {% endif %}User
    </div>
  </div>
  <!-- end class of row -->
  <div class="row no_row_margin">
    <div class="container-fluid">
      <form action="" id="post-form" enctype="multipart/form-data" method="post" role="form" novalidate>
        {% csrf_token %}
        <div class="row form_row no_row_margin">
          <div class="col-md-12">
            <div class="col-md-6">
              {% for field in form %}
                {% if field.name != 'email' and field.name != 'is_active' %}
                  <div class="form-group col-md-12">
                    <label>{{ field.label }} :</label>
                    <div class="controls">
                      {{ field }}
                      {% if field.help_text %}
                      <p class="help-inline"><small>{{ field.help_text }}</small></p>
                      {% endif %}
                    </div>
                  </div>
                {% endif %}
              {% endfor %}
            </div>
            <div class="col-md-6">
              {% for field in form %}
                {% if field.name == 'email' %}
                  <div class="form-group col-md-12">
                    <label>{{ field.label }} :</label>
                    <div class="controls">
                      {{ field }}
                      {% if field.help_text %}
                      <p class="help-inline"><small>{{ field.help_text }}</small></p>
                      {% endif %}
                    </div>
                  </div>
                {% endif %}
                {% if field.name == 'is_active' %}
                  <div class="form-group col-md-12">
                    <label>{{ field.label }}</label>
                    <div class="controls">
                      <select class="form-control" id="id_is_active" name="is_active">
                        <option value="True" {% if field.value %}selected{% endif %}>Active</option>
                        <option value="False" {% if not field.value %}selected{% endif %}>Inactive</option>
                      </select>
                      {% if field.help_text %}
                      <p class="help-inline"><small>{{ field.help_text }}</small></p>
                      {% endif %}
                    </div>
                  </div>
                {% endif %}
              {% endfor %}
            </div>
            <br clear="all">
            <div class=" col-md-12 buttons_row text-left">
              <div class="form-group">
                <button type="submit" class="btn btn-default green_btn"> <i class="fa fa-floppy-o" aria-hidden="true"></i> Save</button>
                <button type="reset" class="btn btn-default blue_btn"> <i class="fa fa-refresh" aria-hidden="true"></i> Reset</button>
              </div>
            </div>
          </div>
      </form>
    </div>
  </div>
  <!-- end div row of form -->
{% endblock %}
{% block js_script %}
  <script type="text/javascript">
    if (window.location.pathname == "{% url 'add_user' %}") {
      $('#page_title').text('Add User');
    } else {
      var user = '{{ user }}';
      $('#page_title').text('Edit User: ' + user);
    }

    $('#post-form').submit(function(event) {
      event.preventDefault();
      $.post(".", $('#post-form').serialize(), function(data) {
        $('p.error').remove();
        if (data.error) {
          $.each(data.response, function(field_name, error) {
            error = "<p class=\"error\">" + error + "</p>"
            $("[name=" + field_name + "]").after(error)
          });
        } else {
          //alert(data['response']);
          window.location = "{% url 'users' %}";
        }
      }, 'json');
    });
  </script>
{% endblock %}

django_blog_it/django_blog_it/templates/dashboard/user/new_list.html
{% extends 'dashboard/new_base.html' %}
{% load paginate %}
{% load blog_tags %}
{% block title %}Users{% endblock %}
{% block extra_css %}
  <style type="text/css">
    table td {
      padding: 6px;
    }
  </style>
{% endblock %}
{% block content %}
  <div class="row no_row_margin heading_count">
    <div class="heading col-md-6">Users</div>
    <div class="count_add-new col-md-6 text-right">
      <ul class="list-inline">
        <li><a href="#">All ({{ users_list|length }}) </a></li>
      </ul>
      <span class="add_new"><a href="{% url 'add_user' %}"><i class="fa fa-plus"></i> Add User</a></span>
    </div>
  </div>
  <div class="filters_row">
    <div class="col-md-6 filter_left">
      {% if request.user.is_superuser %}
        <form class="bulk_actions_form" method='get'>
          {% csrf_token %}
          <select class="form-control" name="bulk_actions_select" id='bulk_actions_select'>
            <option>Choose An Action</option>
            <option value="True">Active</option>
            <option value="False">In-Active</option>
            <option value="Delete">Delete</option>
          </select>
          <button class="btn btn-default" type="submit">Apply Action</button>
        </form>
      {% endif %}
    </div>
    <div class="col-md-6 filter_right">
      <form action="" method="GET" id="users_data" class="form-inline">
        <input type="text" placeholder="Filter By Title" value="{{ request.GET.search_text }}" name='search_text' class="form-control" />
        <select class='input form-control' id="select_role" name="select_role">
          <option value="" default>Role</option>
          {% for role in roles %}
          <option value="{{ role.0 }}" {% ifequal request.GET.select_role role.0 %}Selected{% endifequal %}>{{ role.1 }}</option>
          {% endfor %}
        </select>
        <button class="btn btn-default" type="submit">Apply Filter</button>
      </form>
    </div>
    <br clear="all">
  </div>
  {% if users_list %}
    <div class="row no_row_margin table_row">
      <div class="container-fluid">
        {% paginate 5 users_list %}
        {% show_pageitems %}
        {% with request.user.userrole_set.last as user_role %}
          <table class="table table-bordered table-hover" id="my_table">
            <thead>
              <tr>
                {% if user_role.role != "Author" and user_role.role != "Publisher"%}
                <th width='5%' class="text-center"><input name="bulk_actions" id="selectAll" type="checkbox"></th>
                {% endif %}
                <th width='15%'>Username</th>
                <th width='10%'>First Name</th>
                <th width='10%'>Last Name</th>
                <th width='20%'>Email</th>
                <th width='10%'>Role</th>
                <th width="5%" class="text-center">Status</th>
                {% if request.user.is_superuser or request.user|get_user_role_name == 'Admin' %}
                <th width="5%" class="text-center">Posts</th>
                {% endif %}
                {% if request.user.is_superuser or request.user|get_user_role_name == 'Admin' %}
                <th width='15%' colspan="2">Actions</th>
                {% endif %}
              </tr>
            </thead>
            {% for user in users_list %}
              <tbody>
                <tr>
                  {% if user_role.role != "Author" and user_role.role != "Publisher"%}
                  <td class="text-center"><input name="bulk_actions" class="bulk_actions" value="{{ user.id }}" type="checkbox"></td>
                  {% endif %}
                  <td><a href="#">{{ user.username }}</a></td>
                  <td>{% if user.first_name %}{{ user.first_name }}{% else %}<center> -- </center>{% endif %}</td>
                  <td>{% if user.last_name %}{{ user.last_name }}{% else %}<center> -- </center>{% endif %}</td>
                  <td><a href="#">{{ user.email }}</a></td>
                  <td>{{ user.userrole_set.last.role }}</td>
                  <td class="status_on_off text-center">
                    <a href="{% url 'user_status_update' user.id %}" {% if user.is_active %}class="status_on" title="Active" {% else %} class="status_off" title="In-Active" {% endif %} data-toggle="tooltip" data-placement="bottom"><i class="fa fa-circle" aria-hidden="true"></i></a>
                  </td>
                  {% if request.user.is_superuser or request.user|get_user_role_name == 'Admin' %}
                  <td class="text-center post_count"><a href="#"><span data-toggle="tooltip" data-placement="bottom" title="Drafted">{{ user|user_drafted_posts }}</span> / <span data-toggle="tooltip" data-placement="bottom" title="Published">{{ user|user_published_posts }}</span></a></td>
                  <td class="actions">
                    <a href="{% url 'edit_user' user.id %}" class="edit"><i class="fa fa-edit"></i> Edit</a>
                    <a href="{% url 'delete_user' user.id %}" class="delete" data-confirm="true"><i class="fa fa-trash-o"></i> Delete</a>
                  </td>
                  {% endif %}
                </tr>
              </tbody>
            {% endfor %}
          </table>
        {% endwith %}
        <!-- end div of table -->
        <!-- pagination -->
        <div class="pagination_wrap text-center">
          {% show_pages %}
        </div>
        <!--/ pagination -->
      </div>
    </div>
  {% else %}
    <div class="row no_row_margin table_row">
      <div class="container-fluid">
        <h2 align="center">There are no users here!</h2>
      </div>
    </div>
  {% endif %}
{% endblock %}
{% block js_script %}
  <script type="text/javascript">
    $('.users').addClass('active');
    $(function() {
      $('[data-toggle="tooltip"]').tooltip()
    })

    $('.select2_category').select2({ placeholder: "Select Categories" });

    $("#selectAll").change(function() {
      $(".bulk_actions:checkbox").prop('checked', $(this).prop("checked"));
    });

    $('.bulk_actions_form').submit(function(e) {
      e.preventDefault();
      var user_ids = [];
      $.each($(".bulk_actions:checked"), function() {
        user_ids.push(parseInt($(this).val(), 0));
      });
      var action = $('#bulk_actions_select :selected').val();

      $.get("{% url 'bulk_actions_users' %}", { 'user_ids': user_ids, 'action': action }, function(data) {
        if (data.response) {
          window.location = "{% url 'users' %}";
        } else {
          window.location = "{% url 'users' %}";
        }
      }, 'json');
    });

    // $('.pagination li a').click(function(event){
    //     event.preventDefault();
    //     $('#users_data').attr('action', $(this).attr('href'));
    //     $('#users_data').submit();
    // });
  </script>
{% endblock %}

django_blog_it/django_blog_it/templates/dashboard/user/new_user_role.html
{% extends 'dashboard/new_base.html' %}
{% block title %}
  User Role
{% endblock %}
{% block content %}
  <div class="row no_row_margin heading_count">
    <div class="heading col-md-6" id='page_title'>Edit User Role</div>
  </div>
  <!-- end class of row -->
  <div class="row no_row_margin">
    <div class="container-fluid">
      <form action="" id="post-form" enctype="multipart/form-data" method="post" role="form" novalidate>
        {% csrf_token %}
        <div class="row form_row no_row_margin">
          <div class="form-group">
            <select class='input form-control' id="role" name="role">
              <option value="">Role</option>
              {% for role in roles %}
                <option value="{{ role.0 }}" {% ifequal user_role.0.role role.0 %}Selected{% endifequal %}>{{ role.1 }}</option>
              {% endfor %}
            </select>
          </div>
          <div class=" col-md-12 buttons_row text-left">
            <button type="submit" class="btn btn-default green_btn"> <i class="fa fa-floppy-o" aria-hidden="true"></i> Save</button>
            <button type="reset" class="btn btn-default blue_btn"> <i class="fa fa-refresh" aria-hidden="true"></i> Reset</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <!-- end div row of form -->
{% endblock %}
{% block js_script %}
  <script type="text/javascript">
    $('#post-form').submit(function(event) {
      event.preventDefault();
      $.post("", $('#post-form').serialize(), function(data) {
        if (data.error) {
          $('p.error_required').remove();
          for (var key in data.response) {
            $('#' + key).after('<p class="error_required">* ' + data.response[key] + '</p>');
          }
        } else {
          //alert(data['response']);
          window.location = "{% url 'users' %}";
        }
      }, 'json');
    });
  </script>
{% endblock %}