django_blog_it/django_blog_it/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', admin_login, name='admin_login'),
    url(r'^logout/$', admin_logout, name='admin_logout'),

    # Blog
    url(r'^blog/$', PostList.as_view(), name='blog'),
    url(r'^add/$', PostCreatView.as_view(), name='blog_add'),
    url(r'^view/(?P<blog_slug>[-\w]+)/$', PostDetailView.as_view(), name='view_blog'),
    url(r'^delete/(?P<blog_slug>[-\w]+)/$', PostDeleteView.as_view(), name='delete_blog'),
    url(r'^edit/(?P<blog_slug>[-\w]+)/$', edit_blog, name='edit_blog'),

    # Categories
    url(r'^add_category/$', add_category, name='add_category'),
    url(r'^category/$', categories, name='categories'),
    url(r'^delete_category/(?P<category_slug>[-\w]+)/$', delete_category, name='delete_category'),
    url(r'^edit_category/(?P<category_slug>[-\w]+)/$', edit_category, name='edit_category'),

    url(r'^bulk_actions_menu/$', bulk_actions_menu, name='bulk_actions_menu'),
    url(r'^bulk_actions_blog/$', bulk_actions_blog, name='bulk_actions_blog'),
    url(r'^bulk_actions_category/$', bulk_actions_category, name='bulk_actions_category'),
    url(r'upload_photos/$', upload_photos, name='upload_photos'),
    url(r'recent_photos/$', recent_photos, name='recent_photos'),
]

django_blog_it/django_blog_it/models.py
import datetime
import os
from django.db import models
from django.template.defaultfilters import slugify
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail


ROLE_CHOICE = (
    ('Admin', 'Admin'),
    ('Publisher', 'Publisher'),
    ('Author', 'Author'),
)

STATUS_CHOICE = (
    ('Drafted', 'Drafted'),
    ('Published', 'Published'),
    ('Rejected', 'Rejected'),
    ('Trashed', 'Trashed'),
)


class UserRole(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    role = models.CharField(max_length=10, choices=STATUS_CHOICE)

    class Meta:
        ordering = ['-id']


class Theme(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=500)
    enabled = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Theme, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=500)
    is_active = models.BooleanField(default=False)
    meta_description = models.TextField(max_length=160, null=True, blank=True)
    meta_keywords = models.TextField(max_length=255, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-id']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def category_posts(self):
        return Post.objects.filter(category=self).count()


class Tags(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.CharField(max_length=20, unique=True)

    def save(self, *args, **kwargs):
        tempslug = slugify(self.name)
        if self.id:
            tag = Tags.objects.get(pk=self.id)
            if tag.name != self.name:
                self.slug = create_tag_slug(tempslug)
        else:
            self.slug = create_tag_slug(tempslug)
        super(Tags, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


def create_tag_slug(tempslug):
    slugcount = 0
    while True:
        try:
            Tags.objects.get(slug=tempslug)
            slugcount += 1
            tempslug = tempslug + '-' + str(slugcount)
        except ObjectDoesNotExist:
            return tempslug


class Post(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)
    meta_description = models.TextField(max_length=160, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tags, related_name='rel_posts')
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='Drafted')
    keywords = models.TextField(max_length=500, blank=True)
    featured_image = models.ImageField(upload_to='static/blog/uploads/%Y/%m/%d/', blank=True, null=True)

    class Meta:
        ordering = ['-updated_on']

    def save(self, *args, **kwargs):
        tempslug = slugify(self.title)
        if self.id:
            blogpost = Post.objects.get(pk=self.id)
            if blogpost.title != self.title:
                self.slug = create_slug(tempslug)
        else:
            self.slug = create_slug(tempslug)
            self.email_to_admins_on_post_create()

        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def is_deletable_by(self, user):
        if self.user == user or user.is_superuser:
            return True
        return False

    def create_activity(self, user, content):
        return PostHistory.objects.create(
            user=user, post=self, content=content
        )

    def create_activity_instance(self, user, content):
        return PostHistory(
            user=user, post=self, content=content
        )

    def remove_activity(self):
        self.history.all().delete()

    def email_to_admins_on_post_create(self):
        email = os.getenv("DEFAULT_EMAIL")
        if not self.id and email:
            admin_roles = UserRole.objects.select_related().filter(role="Admin")
            admin_emails = [admin_role.user.email for admin_role in admin_roles]
            user = self.user
            author_name = user.first_name + user.last_name if user.first_name else user.email
            text = "New blog post has been created by {0} with the name {1} in the category {2}.".format(
                author_name, self.title, self.category.name)
            send_mail(
                subject="New Blog Post created",
                message=text,
                from_email=email,
                recipient_list=admin_emails,
                fail_silently=False,
            )

    def store_old_slug(self, old_slug):
        query = Post_Slugs.objects.filter(blog=self, slug=old_slug).values_list("slug", flat=True)
        if not (query and old_slug != self.slug):
            old_slug, _ = Post_Slugs.objects.get_or_create(blog=self, slug=old_slug)
            old_slug.is_active = False
            old_slug.save()
        active_slug, _ = Post_Slugs.objects.get_or_create(blog=self, slug=self.slug)
        active_slug.is_active = True
        active_slug.save()


def create_slug(tempslug):
    slugcount = 0
    while True:
        try:
            Post.objects.get(slug=tempslug)
            slugcount += 1
            tempslug = tempslug + '-' + str(slugcount)
        except ObjectDoesNotExist:
            return tempslug


class Post_Slugs(models.Model):
    blog = models.ForeignKey(Post, related_name='slugs', on_delete=models.CASCADE)
    slug = models.SlugField(max_length=100, unique=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.slug


class PostHistory(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='history', on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{username} {content} {blog_title}'.format(
            username=str(self.user.get_username()),
            content=str(self.content),
            blog_title=str(self.post.title)
        )


class Image_File(models.Model):
    upload = models.FileField(upload_to="static/uploads/%Y/%m/%d/")
    date_created = models.DateTimeField(default=datetime.datetime.now)
    is_image = models.BooleanField(default=True)
    thumbnail = models.FileField(upload_to="static/uploads/%Y/%m/%d/", blank=True, null=True)

    def __str__(self):
        return self.date_created


class ContactUsSettings(models.Model):
    from_email = models.EmailField()
    reply_to_email = models.EmailField(blank=True, null=True)
    email_admin = models.EmailField()
    subject = models.CharField(max_length=500)
    body_user = models.TextField()
    body_admin = models.TextField()


class Google(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='google', on_delete=models.CASCADE)
    google_id = models.CharField(max_length=200, default='')
    google_url = models.CharField(max_length=1000, default='')
    verified_email = models.CharField(max_length=200, default='')
    family_name = models.CharField(max_length=200, default='')
    name = models.CharField(max_length=200, default='')
    picture = models.CharField(max_length=200, default='')
    gender = models.CharField(max_length=10, default='')
    dob = models.CharField(max_length=50, default='')
    given_name = models.CharField(max_length=200, default='')
    email = models.CharField(max_length=200, default='', db_index=True)

    def __str__(self):
        return self.email


class Facebook(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='facebook', on_delete=models.CASCADE)
    facebook_id = models.CharField(max_length=100)
    facebook_url = models.CharField(max_length=200, default='')
    first_name = models.CharField(max_length=200, default='')
    last_name = models.CharField(max_length=200, default='')
    verified = models.CharField(max_length=200, default='')
    name = models.CharField(max_length=200, default='')
    language = models.CharField(max_length=200, default='')
    hometown = models.CharField(max_length=200, default='')
    email = models.CharField(max_length=200, default='', db_index=True)
    gender = models.CharField(max_length=200, default='')
    dob = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=200, default='')
    timezone = models.CharField(max_length=200, default='')
    accesstoken = models.CharField(max_length=2000, default='')

    def __str__(self):
        return self.email

django_blog_it/django_blog_it/templates/dashboard/browse.html
{% load static %}
<html>

<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">
  <title>CKEDitor | Select an image to embed</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/galleriffic/2.0.1/css/basic.min.css" type="text/css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/galleriffic/2.0.1/css/galleriffic-2.min.css" type="text/css" />
  <script type="text/javascript" src="{% static 'ckeditor/galleriffic/js/jquery-1.3.2.js' %}"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/galleriffic/2.0.1/jquery.galleriffic.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/galleriffic/2.0.1/jquery.opacityrollover.min.js"></script>
  <!-- We only want the thunbnails to display when javascript is disabled -->
  <script type="text/javascript">
  document.write('<style>.noscript { display: none; }</style>');
  </script>
</head>

<body>
  <div id="page">
    <div id="container" style="width: 880px">
      {% ifequal files|length 0 %}
        <h2>No images found. Upload images using the 'Image Button' dialog's 'Upload' tab.</h2>
      {% endifequal %}
      <!-- Start Advanced Gallery Html Containers -->
      <div id="gallery" class="content">
        <div class="slideshow-container">
          <div id="loading" class="loader"></div>
          <div id="slideshow" class="slideshow"></div>
        </div>
        <div id="caption" class="caption-container"></div>
      </div>
      <div id="thumbs" class="navigation">
        <ul class="thumbs noscript">
          {% for file in files %}
            <li>
              <a {% if file.is_image %}class="thumb" {% endif %} href="{{ file.src }}">
                {% if file.is_image %}
                  <img src="{{ file.thumb }}" style="max-width: 75px;" />
                {% else %}
                  {{ file.thumb }}
                {% endif %}
              </a>
              <div class="caption">
                <div class="submit-row">
                  <input href="{{ file.src }}" class="default embed" type="submit" name="_embed" value="Embed Image" />
                </div>
              </div>
            </li>
          {% endfor %}
        </ul>
      </div>
      <div style="clear: both;"></div>
    </div>
  </div>
  <script type="text/javascript">
    // helper functions
    function getUrlParam(paramName) {
      var reParam = new RegExp('(?:[\?&]|&amp;)' + paramName + '=([^&]+)', 'i');
      var match = window.location.search.match(reParam);

      return (match && match.length > 1) ? match[1] : '';
    }

    function scale_image() {
      var max_width = 500;
      var image = $(".advance-link > img");
      var image_width = image.width();
      if (image_width > max_width) {
        var aspect = image.height() / image_width;
        var image_height = max_width * aspect;
        image.width(max_width);
        image.height(image_height);
      }
    }

    // embedder
    $('.embed').live('click', function() {
      var funcNum = getUrlParam('CKEditorFuncNum');
      var fileUrl = $(this).attr('href');
      window.opener.CKEDITOR.tools.callFunction(funcNum, fileUrl);
      window.close();
    });

    // galleriffic
    jQuery(document).ready(function($) {
      // We only want these styles applied when javascript is enabled
      $('div.navigation').css({ 'width': '300px', 'float': 'left' });
      $('div.content').css('display', 'block');

      // Initially set opacity on thumbs and add
      // additional styling for hover effect on thumbs
      var onMouseOutOpacity = 0.67;
      $('#thumbs ul.thumbs li').opacityrollover({
        mouseOutOpacity: onMouseOutOpacity,
        mouseOverOpacity: 1.0,
        fadeSpeed: 'fast',
        exemptionSelector: '.selected'
      });

      // Initialize Advanced Galleriffic Gallery
      var gallery = $('#thumbs').galleriffic({
        delay: 2500,
        numThumbs: 15,
        preloadAhead: 10,
        enableTopPager: true,
        enableBottomPager: true,
        maxPagesToShow: 7,
        imageContainerSel: '#slideshow',
        controlsContainerSel: '#controls',
        captionContainerSel: '#caption',
        loadingContainerSel: '#loading',
        renderSSControls: true,
        renderNavControls: true,
        playLinkText: 'Play Slideshow',
        pauseLinkText: 'Pause Slideshow',
        prevLinkText: '&lsaquo; Previous Photo',
        nextLinkText: 'Next Photo &rsaquo;',
        nextPageLinkText: 'Next &rsaquo;',
        prevPageLinkText: '&lsaquo; Prev',
        enableHistory: false,
        autoStart: false,
        syncTransitions: false,
        defaultTransitionDuration: 500,
        onSlideChange: function(prevIndex, nextIndex) {
          // 'this' refers to the gallery, which is an extension of $('#thumbs')
          this.find('ul.thumbs').children()
            .eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
            .eq(nextIndex).fadeTo('fast', 1.0);
        },
        onPageTransitionOut: function(callback) {
          this.fadeTo('fast', 0.0, callback);
        },
        onPageTransitionIn: function() {
          this.fadeTo('fast', 1.0);
        },
        onTransitionIn: function(newSlide, newCaption, isSync) {
          scale_image();
          newSlide.fadeTo(this.getDefaultTransitionDuration(isSync), 1.0);
          if (newCaption)
            newCaption.fadeTo(this.getDefaultTransitionDuration(isSync), 1.0);
        }
      });
    });
  </script>
</body>

</html>

django_blog_it/django_blog_it/templates/dashboard/new_admin-login.html
{% extends 'dashboard/new_base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block body_block %}login_body{% endblock body_block %}
{% block main_content %}
  <!-- welcome meassge ends here -->
  <!-- Description starts here -->
  <div class="row no_row_margin login_block">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <div class="account-wall">
        <div id="__all__" class="tab-content">
          <form class="form-signin" action="" method="post" id="admin_login_form" novalidate>
            {% csrf_token %}
            <input type="text" name="username" id="username" class="form-control" placeholder="Username" autofocus>
            <input type="password" name="password" id="password" class="form-control" placeholder="Password">
            <input type="submit" class="btn btn-lg btn-default btn-block" value="Sign In" />
            <div>
              <a href="{% url 'google_login' %}"> Sign in with Google </a>
            </div>
            <div>
              <a href="{% url 'facebook_login' %}"> Sign in with Facebook </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- Description ends here -->
{% endblock main_content %}
{% block js_script %}
  <script type="text/javascript">
    $("#admin_login_form").submit(function(e) {
      e.preventDefault();
      $.post(".", $("#admin_login_form").serialize(), function(data) {
        if (data.error) {
          $('p.login_error_required').remove();
          for (var key in data.errors) {
            if (key == '__all__') {
              $('#' + key).after("<p class='login_error_required text-center'>&nbsp;&nbsp; * " + data.errors[key] + "</p>");
            } else {
              $('#' + key).after("<p class='login_error_required'>&nbsp;&nbsp; * " + data.errors[key] + "</p>");
            }
          }
        } else {
          //alert(data['response']);
          window.location = "{% url 'blog' %}";
        }
      }, "json")
    });
  </script>
{% endblock %}

django_blog_it/django_blog_it/templates/dashboard/new_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Dashboard - {% block title %}Home{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <!-- for online links -->
    <link rel="shortcut icon" href="{%static 'images/favicon.png' %}">
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <!--select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />
    <!-- // -->
    <!-- for tags -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.tagsinput.css' %}" />
    <!-- // -->
    {% block extra_css %}
    {% endblock %}
  </head>
  <body class="{% block body_block %}{% endblock body_block %}">
    <div id="wrapper">
      {% block main_content %}
        {% if request.user.is_active %}
        {% block menu_block %}
          <header class="row no_row_margin">
            <nav class="navbar navbar-default">
              <div class="container-fluid">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="{% url 'index' %}">Django Blog</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li class="dashboard"><a href="{% url 'admin_login' %}">Dashboard <span class="sr-only">(current)</span></a></li>
                  <!-- <li class="dropdown">
                    <a href="{% url 'categories' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><a href="#">Action</a></li>
                      <li><a href="#">Another action</a></li>
                      <li><a href="#">Something else here</a></li>
                      <li><a href="#">One more separated link</a></li>
                    </ul>
                  </li> -->
                  <li class="categories"><a href="{% url 'categories' %}">Categories </a></li>
              {% with request.user.userrole_set.last as user_role %}
                {% if request.user.is_superuser or user_role.role == "Admin"%}
                  <li class="users"><a href="{% url 'users' %}">Users </a></li>
                {% endif %}
              {% endwith %}
                  <li class="themes"><a href="{% url 'themes' %}">Themes</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{request.user}} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'change_password' %}"><i class="fa fa-key" aria-hidden="true"></i> Change Password</a></li>
                      <li><a href="{% url 'admin_logout' %}"><i class="fa fa-sign-out"></i> Logout</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
              <!--   <div class="row menu_items">
                  <ul class="nav nav-pills pull-left">
                    <li role="presentation" id="home"><a href="/dashboard/blog">Home</a></li>
                    <li role="presentation" id="categories"><a href="{% url 'categories' %}">Categories</a></li>
                    <li role="presentation" id="users"><a href="{% url 'users' %}">Users</a></li>
                  </ul>
                  <p class="pull-right">
                    <a href="{% url 'admin_logout' %}">
                    <button class="btn btn-danger"><i class="fa fa-sign-out"></i> Logout</button>
                    </a>
                  </p>
                </div> -->
              </div>
            </nav>
          </header>
          {% endblock %}
          {% endif %}
            {% if messages %}
              {% for message in messages %}
              <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible my_alert" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>{% if message.tags %}{{ message.tags|title }} !{% endif %}</strong> {{ message }}.
              </div>
              {% endfor %}
            {% endif %}
            <div class="main_container">
              <div class="row no_row_margin">
              {% block content %}
              {% endblock content %}
              </div>
            </div>
            <footer class="my_footer">
            </footer>
      {% endblock main_content %}
    </div>
    <!-- end div container -->
    <!-- for online links  -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
    <script src="//malsup.github.com/jquery.form.js"></script>
    <!-- <script src="//cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script> -->
    <script src="https://cdn.ckeditor.com/ckeditor5/17.0.0/classic/ckeditor.js"></script>
    <script src="{% static 'js/jquery.tagsinput.js' %}"></script>
    <script type="text/javascript">
      $('.select2').select2(
        {
            tags: "true",
            placeholder: "Select an option"
        }
      );
      {% block delete_confirmation %}
        // for delete confirmation
        $('*[data-confirm="true"]').on('click', function() {
            return confirm("Are you sure?");
        });
      {% endblock delete_confirmation %}
      // for pagination
      $('.pagination li a.active').each(function(){
          $(this).css('background', '#337AB7');
          $(this).css('color', '#fff');
      });

      if($('.pagination li:first').find('a span').text() == '<<'){
          $('.pagination li:first').find('a span').text('First');
      }

      if($('.pagination li:nth-child(2)').find('a span').text() == '<'){
          $('.pagination li:nth-child(2)').find('a span').text('Prev');
      }

      if($('.pagination li:last').find('a span').text() == '>>'){
          $('.pagination li:last').find('a span').text('Last');
      }
      if($('.pagination li:nth-last-child(2)').find('a span').text() == '>'){
          $('.pagination li:nth-last-child(2)').find('a span').text('Next');
      }

      $(document).ready(function() {
        setTimeout(function() {
          $('.my_alert').fadeOut(2000, function(){});
        }, 3000);
      });
    </script>
    {% block js_script %}
    {% endblock %}
  </body>
</html>

django_blog_it/django_blog_it/templates/dashboard/new_contact_us_settings.html
{% extends 'dashboard/new_base.html' %}
{% load static %}
{% block title %}
Configure Contact Us.
{% endblock %}
{% block extra_css %}
{% endblock %}
{% block content %}
<div class="row no_row_margin heading_count">
  <div class="heading col-md-6" id='page_title'></div>
</div>
<div class="row no_row_margin">
  <div class="container-fluid">
    <form action="" method="post" id="contact-us-configure-form" role="form">
      {% csrf_token %}
      <div class="row form_row no_row_margin">
        <div class="col-md-12">
          <div class="col-md-6">
            {% for field in form %}
              {% if field.name != 'email_admin' and field.name != 'subject' and field.name != 'body_admin' %}
                <div class="form-group">
                  <label>{{ field.label }} :</label>
                  <div class="controls">
                    {{ field }}
                    {% if field.help_text %}
                    <p class="help-inline"><small>{{ field.help_text }}</small></p>
                    {% endif %}
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </div>
          <div class="col-md-6">
            {% for field in form %}
              {% if field.name == 'email_admin' or field.name == 'subject' or field.name == 'body_admin' %}
                <div class="form-group">
                  <label>{{ field.label }} :</label>
                  <div class="controls">
                    {{ field }}
                    {% if field.help_text %}
                    <p class="help-inline"><small>{{ field.help_text }}</small></p>
                    {% endif %}
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </div>
        </div>
        <br clear="all">
        <div class=" col-md-12 buttons_row text-left">
          <button type="submit" class="btn btn-default green_btn"> <i class="fa fa-floppy-o" aria-hidden="true"></i> Save</button>
          <button type="reset" class="btn btn-default blue_btn"> <i class="fa fa-refresh" aria-hidden="true"></i> Reset</button>
        </div>
      </div>
    </form>
  </div>
</div>
<!-- end of add form div -->
{% endblock content %}
{% block js_script %}

<script type="text/javascript">
  $(document).ready(function(){

    // for form submission
    /*CKEDITOR.replace('body_user',{
      filebrowserUploadUrl: '{% url "upload_photos" %}',
      filebrowserBrowseUrl: '{% url "recent_photos" %}',
      uiColor: '#ffffff',
      height: 175,
    });
    CKEDITOR.replace('body_admin',{
      filebrowserUploadUrl: '{% url "upload_photos" %}',
      filebrowserBrowseUrl: '{% url "recent_photos" %}',
      uiColor: '#ffffff',
      height: 175,
    });*/

    ClassicEditor
      .create( document.querySelector( '#id_body_user' ) )
      .then( newEditor => {
          window.userEditor = newEditor;
      } )
      .catch( error => {
          console.error( error );
      } );

    ClassicEditor
      .create( document.querySelector( '#id_body_admin' ) )
      .then( newEditor => {
          window.adminEditor = newEditor;
      } )
      .catch( error => {
          console.error( error );
      } );
  });

  $('#contact-us-configure-form').submit(function(event){
      event.preventDefault();
      $('#id_body_user').val(window.userEditor.getData());
      $('#id_body_admin').val(window.adminEditor.getData());
      $.post("",$('#contact-us-configure-form').serialize(), function(data){
          if(data.error){
              $('p.error_required').remove();
              for (var key in data.response) {
                  $('#id_' + key).after('<p class="error_required">* ' + data.response[key] + '</p>');
              }
          }else{
              //alert(data['response']);
              window.location='{% url "blog" %}';
          }
      }, 'json');
  });
</script>
{% endblock %}